redeye_graphql_single_endpoint:
    resource: "@RedeyeGraphQLBundle/Resources/config/routing/single.yaml"
    prefix: /

redeye_graphql_multiple_endpoint:
    resource: "@RedeyeGraphQLBundle/Resources/config/routing/multiple.yaml"
    prefix: /graphql
