redeye_graphql_multiple_endpoint:
    path: /{schemaName}
    defaults:
        _controller: Redeye\GraphQLBundle\Controller\GraphController::endpointAction
        _format: "json"
    requirements:
        schemaName: '[^/]+'

redeye_graphql_batch_multiple_endpoint:
    path: /{schemaName}/batch
    defaults:
        _controller: Redeye\GraphQLBundle\Controller\GraphController::batchEndpointAction
        _format: "json"
    requirements:
        schemaName: '[^/]+'
