redeye_graphql_endpoint:
    path: /
    defaults:
        _controller: Redeye\GraphQLBundle\Controller\GraphController::endpointAction
        _format: "json"

redeye_graphql_batch_endpoint:
    path: /batch
    defaults:
        _controller: Redeye\GraphQLBundle\Controller\GraphController::batchEndpointAction
        _format: "json"
