services:
    _defaults:
        public: true

    Redeye\GraphQLBundle\Command\GraphQLDumpSchemaCommand:
        arguments:
            - "%kernel.cache_dir%/../.."
            - '@Redeye\GraphQLBundle\Request\Executor'
        tags:
            - { name: console.command, command: graphql:dump-schema, alias: "graph:dump-schema" }

    Redeye\GraphQLBundle\Command\DebugCommand:
        arguments:
            - '@Redeye\GraphQLBundle\Resolver\TypeResolver'
            - '@Redeye\GraphQLBundle\Resolver\MutationResolver'
            - '@Redeye\GraphQLBundle\Resolver\QueryResolver'
        tags:
            - { name: console.command, command: graphql:debug, alias: "debug:graphql" }

    Redeye\GraphQLBundle\Command\CompileCommand:
        arguments:
            - '@Redeye\GraphQLBundle\Generator\TypeGenerator'
        tags:
            - { name: console.command, command: graphql:compile }

    Redeye\GraphQLBundle\Command\ValidateCommand:
        arguments:
            - '@Redeye\GraphQLBundle\Request\Executor'
        tags:
            - { name: console.command, command: graphql:validate }
