services:
    Redeye\GraphQLBundle\Definition\ConfigProcessor\PublicFieldsFilterConfigProcessor:
        tags:
            - { name: redeye_graphql.definition_config_processor, priority: 2048 }

    Redeye\GraphQLBundle\Definition\ConfigProcessor\AclConfigProcessor:
        arguments:
            - '@Redeye\GraphQLBundle\Resolver\AccessResolver'
            - "@redeye_graphql.default_field_resolver"
        tags:
            - { name: redeye_graphql.definition_config_processor, priority: 512 }

    Redeye\GraphQLBundle\Definition\ConfigProcessor\WrapArgumentConfigProcessor:
        arguments:
            - '@Redeye\GraphQLBundle\Definition\ArgumentFactory'
        tags:
            - { name: redeye_graphql.definition_config_processor }
