services:
    # GraphQL build-in Scalars types
    redeye_graphql.definition.string_type:
        class: GraphQL\Type\Definition\StringType
        factory: [GraphQL\Type\Definition\Type, string]
        tags:
            - { name: redeye_graphql.type, alias: String }

    redeye_graphql.definition.int_type:
        class: GraphQL\Type\Definition\IntType
        factory: [GraphQL\Type\Definition\Type, int]
        tags:
            - { name: redeye_graphql.type, alias: Int }

    redeye_graphql.definition.float_type:
        class: GraphQL\Type\Definition\FloatType
        factory: [GraphQL\Type\Definition\Type, Float]
        tags:
            - { name: redeye_graphql.type, alias: Float }

    redeye_graphql.definition.boolean_type:
        class: GraphQL\Type\Definition\BooleanType
        factory: [GraphQL\Type\Definition\Type, boolean]
        tags:
            - { name: redeye_graphql.type, alias: Boolean }

    redeye_graphql.definition.id_type:
        class: GraphQL\Type\Definition\IDType
        factory: [GraphQL\Type\Definition\Type, id]
        tags:
            - { name: redeye_graphql.type, alias: ID }
