services:
    Redeye\GraphQLBundle\EventListener\RequestFilesListener:
        arguments:
            - "@request_stack"
        tags:
            - { name: kernel.event_listener, event: graphql.executor.context, method: onExecutorContextEvent }

    Redeye\GraphQLBundle\EventListener\TypeDecoratorListener:
        arguments:
            - '@Redeye\GraphQLBundle\Definition\ArgumentFactory'
        tags:
            - { name: kernel.event_listener, event: graphql.type_loaded, method: onTypeLoaded }

    Redeye\GraphQLBundle\EventListener\ValidationErrorsListener:
        tags:
            - name: kernel.event_listener
              event: !php/const Redeye\GraphQLBundle\Event\Events::ERROR_FORMATTING
              method: onErrorFormatting
