services:
    Redeye\GraphQLBundle\Controller\ProfilerController:
        public: true
        arguments:
            - "@?profiler"
            - "@?twig"
            - "@router"
            - '@Redeye\GraphQLBundle\Request\Executor'
            - "%redeye_graphql.profiler.query_match%"

    Redeye\GraphQLBundle\DataCollector\GraphQLCollector:
        public: false
        tags:
            - name: data_collector
              template: "@RedeyeGraphQL/profiler/panel.html.twig"
              id: graphql
            - { name: kernel.event_listener, event: graphql.post_executor, method: onPostExecutor }
